### ISSUE TITLE
server side rendering support

### ISSUE THREAD

**Issue by martunta** [mars/create-react-app-buildpack#104]
I have been looking around on how to adapt this buildpack to server side rendering and create-react-app. My usecase is as simple as it gets - there are small node/express script that interprets request url and then injects appropriate meta tags (facebook sharing, as could be expected) into built html and then serves it back to the client.

this is not exactly like the scenario you have described in html, where both node API and static React  app are bundled together in one buildpack and then API is proxied via react app. In this case I only have react app with some injected meta tags, API is still very separate. 

Can you please show any way forward? Thanks in advance!

**Comment by mars** [comment]
This buildpack is never going to help you implement dynamic server-side behavior (unless create-react-app itself somehow provides it, but they say it will not ever be supported directly).

Starting with [heroku-cra-node](https://github.com/mars/heroku-cra-node) (create-react-app + Node server on Heroku) reference app is the way to go if you want to roll your own. Sounds like you don't need an API, which is fine, but that reference app is still the best way to see how to get Node server deployed along with create-react-app. Then in `server/index.js`, you'll implement Express handlers & template rendering to inject tags into `public/index.html`.

Reality check: server-side rendering in the context of client-side apps get complicated quickly. (e.g. What happens when the browser navigates to a new route and you want to rewrite the HTML again?)

I would recommend switching to [Next.js](https://nextjs.org), a universal web app (server-rendered) framework based on React. Next.js offers so many more useful features than plain create-react-app (`pages/` file-based routes, bundle splitting, data fetching hooks, etc.), I personally don't use CRA anymore. Next.js server-rendering is amazing ✨ Here's a [Next.js on Heroku](https://github.com/mars/heroku-nextjs) reference app.

**Comment by martunta** [comment]
I want inject those meta tags only in the cases when facebook accesses the page after share button is pressed. So it will be always static, facebook is not going to navigate anywhere. And for user any subsequent route changes will be handled by react router fully on client side. 

but alas, if it is not possible, then it is not possible. Is that reference app is going to help me with figuinrg out the buildpack? As I have all the tag injection already working, just need to make sure that after building npm start gets executed instead of static file serving. 

Our app is heavy with Three.js - there is no way it can be rendered on server side, so I am afraid that with next.js there might be need to build workarounds to ensure that 3D part of the code is not touched. 

So, switching to Next.js for relatively complex project that has been built for several years is feels like larger undertaking compared to figuring out how to run execute 30 lines of nodejs code after build has been done. 

But maybe things have changed since I last looked into it. will check it out at soon. but only after I fix current issue :)

**Comment by mars** [comment]
That heroku-cra-node reference app does not use this buildpack. It's a pure [heroku/nodejs](https://github.com/heroku/heroku-buildpack-nodejs) app that runs Express via `npm start`.
