### ISSUE TITLE
App not compatible with buildpack

### ISSUE THREAD

**Issue by feimosi** [mars/create-react-app-buildpack#135]
I've started receiving the following error:
`App not compatible with buildpack: https://github.com/mars/create-react-app-buildpack.git`
even though yesterday the build was running smoothly. I haven't changed anything in my project, if I force push the same commit as on the remote it fails anyway.

**Comment by mars** [comment]
For this buildpack, that "App not compatible" error means `package.json` is not at the root of the repo.

Please paste the output of the following commands from your app/repo to help debug:

```bash
heroku buildpacks

git status

ls -hal
```

**Comment by feimosi** [comment]
So it's not exactly in the root folder but in the `frontend` subfolder. The root is empty and it's been really working for the last month without any problems

```
 heroku buildpacks
=== Buildpack URL
https://github.com/mars/create-react-app-buildpack.git

 git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
~/Projects/saycaster-podcatcher

 ls -hal
total 20K
drwxr-xr-x 4 feimosi users 4.0K Oct 11 08:24 .
drwxr-xr-x 7 feimosi users 4.0K Oct  7 19:23 ..
drwxr-xr-x 9 feimosi users 4.0K Oct 11 08:24 frontend
drwxr-xr-x 7 feimosi users 4.0K Oct 11 08:24 .git
```

**Comment by mars** [comment]
Heroku’s build system does not support apps in subdirectories.

The only way to make this work as-is would be using the community-contributed [monorepo buildpack](https://github.com/lstoll/heroku-buildpack-monorepo), which basically moves an app into the root for deployment.

I advise changing the repo layout to have the app at the root, because adding that monorepo buildpack will just make things more complicated and possibly harder to debug issues down the line.

The fact that it was working was some kind of fluke 🤭 I think you stumbled upon an old Heroku platform build workaround to support the no-longer-available Deploy from DropBox workflow. Based on your experience that undocumented single-subdirectory deploy trick is no-longer-available either.
