### ISSUE TITLE
High memory consumption - is there anything one can do?

### ISSUE THREAD

**Issue by donatoaz** [mars/create-react-app-buildpack#140]
I am running a simple SPA, nothing fancy, but each time I deploy I get several memory exceed errors on my Hobby tier dyno.

Is there anything I can do to debug or optimize this?

![image](https://user-images.githubusercontent.com/127527/48780833-f18a0e00-ecc1-11e8-9ebf-c74c07aedd6b.png)

**Comment by mars** [comment]
Hi @donatoaz 😄

That high memory usage does seem strange, because this buildpack launches Nginx to serve the React build. It typically consumes less than 30MB memory.

Wondering if you are launching a different process:

Have you defined a `Procfile`? If so, what does it contain?

Otherwise, have you combined this app with more buildpacks? What does `heroku buildpacks` return?

**Comment by mars** [comment]
Do you have a lot of traffic/visitors to your app?

**Comment by donatoaz** [comment]
Hi @mars thanks so much for the attention. **It is totally my fault.** I had the buildpack set up on the prod env (which is also a paid dyno) and therefore had a really low mem consumption, but not on my staging env -- which was still using heroku's own `heroku/nodejs`.

All good now (see before/after shot when I changed to your buildpack 🎉)
![image](https://user-images.githubusercontent.com/127527/48953297-7e380480-ef2c-11e8-8674-3f9848f951ec.png)


```
heroku buildpacks --app ctw-staging
=== ctwportal Buildpack URL
mars/create-react-app
```
