### ISSUE TITLE
HTTPS-only does not work

### ISSUE THREAD

**Issue by j4nos** [mars/create-react-app-buildpack#166]
I did set static.json as show in doc, but still http is allowed. What am I doing wrong?
<img width="911" alt="Képernyőfotó 2019-11-12 - 9 57 05" src="https://user-images.githubusercontent.com/11924475/68656812-ce8be600-0532-11ea-95e1-79ac72f2941f.png">

<img width="553" alt="Képernyőfotó 2019-11-12 - 9 57 30" src="https://user-images.githubusercontent.com/11924475/68656840-dd729880-0532-11ea-9ba1-b6d816fa0a60.png">

**Comment by mars** [comment]
HTTPS is only supported when deployed to Heroku with this buildpack.

Are you trying to use HTTPS locally? Local create-react-app dev is plain HTTP only.

Otherwise confirm that you’re actually deploying that change. Is the HTTPS config on a branch other than master? If so you may accidentally be deploying the wrong branch. To push a non-master branch to Heroku:

```bash
git push heroku other-branch:master
```

*Set `other-branch` to your local branch you wish to deploy.*

**Comment by j4nos** [comment]
static.json 

```
{
  "root": "build/",
  "routes": {
    "/**": "index.html"
  },
  "https_only": true,
  "headers": {
    "/**": {
      "Strict-Transport-Security": "max-age=31557600"
    }
  }
}
```

worked

**Comment by ricardolpd** [comment]
@j4nos I am having a similar issue, but it wont work with `Strict-Transport-Security` header either, i noticed your static.json is not in the root folder. Is ur static.json in the same folder as your `Procfile`?
