### ISSUE TITLE
Build fails on Heroku servers

### ISSUE THREAD

**Issue by CodeJjang** [mars/create-react-app-buildpack#17]
Hi,

Getting:

```
remote: > react-scripts build
remote:
remote: Creating an optimized production build...
remote: Failed to compile.
remote:
remote: Module not found: Error: Cannot resolve 'file' or 'directory' ./Routes in /tmp/build_e872953b462d7462b7b922188eb98d08/src
```

After pushing to Heroku, even though `npm run build` runs fine locally.
Any idea?

**Comment by mars** [comment]
If it builds locally but not on push, then there's probably an uncommitted difference in your local directory.

What does `git status` return?

**Comment by CodeJjang** [comment]
I checked, nothing to commit. That's why I came here... this is very weird. 
Thought it might be an issue with the buildpack script.

**Comment by CodeJjang** [comment]
I have a suspicious tho.
I changed a referenced file from ./routes to ./Routes.
Maybe in the remote Heroku git the change is not recognized, and the file routes.js is left lowercase on the git filesystem somehow?

Edit: I can confirm that on github.com on my develop branch  I see the lowercased file routes.js instead of being Routes.js even though I pushed changes.
Somehow git doesnt recognize this and doesn't push the changes.

**Comment by mars** [comment]
Capitalization must be consistent. Linux (the OS used in the Heroku runtime) is case sensitive, so the difference in case will break require/import statements. Even though it seems to work locally, they are different file names.

Because of the way consumer OSs like Mac & Windows ignore case, this kind of problem is an easy mistake to make.

This is an unfortunately sticky problem to recover from, but it is great you noticed the difference!

**Comment by DarkKnight1992** [comment]
@CodeJjang thanks i was banging my head for hours until i change git to register case changes
