### ISSUE TITLE
Cant push to heroku

### ISSUE THREAD

**Issue by Jony-Y** [mars/create-react-app-buildpack#20]
Hi, I keep getting 

> remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Failed to detect set buildpack https://github.com/heroku/heroku-buildpack-static.git
remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to ready4-web-staging.
remote: 

when trying to push.
I followed the instructions can you please help?

p.s - general question, if I only want to push to heroku from the build folder, would that be problematic? naturally the static.json will need to be imported there and the root change

**Comment by mars** [comment]
The "failed to detect" error for static-buildpack indicates that `static.json` is missing, which does not make sense because this buildpack generates one by default.

This is very little information to diagnose. Please update with full build log, output of `heroku buildpacks`, and if possible read access to a Github repo with your source code.

Answer to your general question: no, this buildpack runs the build on Heroku, creating `build/` for you. Pushing only a build folder is not compatible with this buildpack; it requires the whole create-react-app project/repo. You could use the Heroku static-buildpack alone to deploy only a pre-built app: https://github.com/heroku/heroku-buildpack-static

**Comment by Jony-Y** [comment]
Hi, thanks for the quick answer.
I managed to solve it by deleting the project and running the commands again, I guess I missed something on the way.

thanks

**Comment by wung-s** [comment]
@Jony-Y ran into the same issue. After reading @mars comment, realized that I was doing trying to push the built code i.e from within the `/build` directory
Pushing the code from the `root` directory resolved the issue. Saved me a whole lot of time. Thanks  @mars

**Comment by Jony-Y** [comment]
@wung-s yeah, thats what I ended up doing as well. thanks :)
