### ISSUE TITLE
Question regarding routing

### ISSUE THREAD

**Issue by CodeJjang** [mars/create-react-app-buildpack#21]
Hi,

I use react-router and react-router-redux inside my app.  
When I access the root URL of the app, I receive the page. However when accessing directly to a specific path, I get nginx 404 error.  
This does not happen locally.  

I assumed nginx needs to be configured, but I saw you allow to add a `static.json` file which does:
```
{
  "root": "build/",
  "clean_urls": false,
  "routes": {
    "/**": "index.html"
  }
}
```
This seems like it should fix the problem but it doesnt.

Any idea?

**Comment by gitgrimbo** [comment]
Are you deploying to heroku? I think that's a heroku-specific file - https://github.com/heroku/heroku-buildpack-static - rather than an nginx file.

**Comment by gitgrimbo** [comment]
Would this config from https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md help?

*If you're using nginx, use the [try_files directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files):*

```
server {
  ...
  location / {
    try_files $uri /index.html;
  }
}
```

**Comment by mars** [comment]
Hi @CodeJjang , sorry for my delay in responding, I have been traveling & finally found time to respond.

Using `static.json` to configure clean URLs (to support HTML5 pushState) is the correct approach.

If it is not working for you, please confirm that it's setup correctly:

1. `static.json` as [described in README](https://github.com/mars/create-react-app-buildpack#routing-clean-urls) must be added & committed to the git repo:

    ```bash
    git add static.json
    git commit -m 'Configure clean URLs'
  
    # Then redeploy
    git push heroku master
    ```
1. React Router must be configured to use [`browserHistory`](https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md#histories).

Since you mention that clean URLs work locally, my guess is that it is not correctly committed to git.

@gitgrimbo Thanks for your suggestions! The Nginx server is not directly exposed in this buildpack, so direct configuration is not possible. `static.json` provides a curated set of options for HTML5+Javascript apps.

**Comment by mars** [comment]
@CodeJjang did you solve this problem?
