### ISSUE TITLE
Possible to do runtime config with variable in html?

### ISSUE THREAD

**Issue by mtwomey** [mars/create-react-app-buildpack#38]
I have an app which I'm trying to deploy to Heroku that has this:

    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=%REACT_APP_GOOGLE_API_KEY%">
    </script>

I understand the method for runtime variables when they're in JS services / components - but is it possible to achieve this here?

**Comment by mars** [comment]
I *believe* that script tag could be programmatically generated from within the React app, so that the runtime env is accessible:

```javascript
// Acquire the runtime environment in the normal way:
import runtimeEnv from '@mars/heroku-js-runtime-env';

class App extends React.Component {

  // Use DOM API directly to inject the script tag:
  componentDidMount() {
    const env = runtimeEnv();
    const script = document.createElement("script");
    script.src = `//maps.googleapis.com/maps/api/js?key=${env.REACT_APP_GOOGLE_API_KEY}`;
    script.async = true;
    document.body.appendChild(script);
  }

}
```

Note that this kind of tag injection should be in the top-level `App` component, so that it will not get re-injected as the component goes through mount/unmount cycles.

**Comment by mtwomey** [comment]
Yeah - ok makes sense. I will give it a shot and thank you!
