### ISSUE TITLE
HTTPS only not working

### ISSUE THREAD

**Issue by fbarbare** [mars/create-react-app-buildpack#39]
Hi,

I created a `static.json` and added the following things:
```
{
  "root": "build/",
  "clean_urls": false,
  "https_only": true,
  "routes": {
    "/**": "index.html"
  },
  "headers": {
    "/**": {
      "Strict-Transport-Security": "max-age=7776000"
    }
  }
}
```

But it does not redirect any request, it doesn't seem to pick up the `static.json` file at all.

Thanks for help!

**Comment by mars** [comment]
Is that `static.json` committed at the root-level & deployed?

**Comment by fbarbare** [comment]
It is... I tried to change the root path to see if the app was gonna start failing but it did not, that's what lets me think the `static.json` is not being picked up.. And it's weird.
If it is being read, am I supposed to see something in the logs or something?

**Comment by fbarbare** [comment]
You can actually see the repo there: https://github.com/fbarbare/blog-admin

**Comment by mars** [comment]
In the log lines from this buildpack, you will see one of two messages about `static.json` (output from here https://github.com/mars/create-react-app-inner-buildpack/blob/master/bin/compile#L34 ).

When a custom config is supplied, it should output:

> Using existing `static.json`.

It's not clear to me what's going wrong. Thanks for linking your code repo. I'll try to reproduce later today.

**Comment by fbarbare** [comment]
It actually says
> Using existing `static.json`

in the build logs but nothing on run time.

**Comment by mars** [comment]
I just checked out & deployed your app, and see that an Express (Node) server is responding to requests:

```bash
$ curl -I cra-b-issue-39.herokuapp.com
HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express   ###   <---- This is from Node.
Accept-Ranges: bytes
Cache-Control: public, max-age=0
Last-Modified: Sun, 26 Mar 2017 23:29:58 GMT
Etag: W/"46c-15b0cf470f0"
Content-Type: text/html; charset=UTF-8
Content-Length: 1132
Vary: Accept-Encoding
Date: Sun, 26 Mar 2017 23:32:20 GMT
Via: 1.1 vegur
```

This is why `static.json` has no effect, the `Procfile` in the repo is overriding the built-in web server with `npm start` running create-react-app/react-scripts in *development* mode (for local, hot-reloading of changes to React code).

**To fix, delete the `Procfile` and deploy.** The buildpack automates building an optimized *production* bundle and serving it from a high-performance [static web server](https://github.com/heroku/heroku-buildpack-static).

Then, the `static.json` config will be honored.

```bash
$ curl -I cra-b-issue-39.herokuapp.com
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Server: nginx   ###   <---- This is from Nginx static server.
Date: Sun, 26 Mar 2017 23:42:44 GMT
Content-Type: text/html
Content-Length: 178
Strict-Transport-Security: max-age=7776000
Location: https://cra-b-issue-39.herokuapp.com/   ###   <---- HTTPS redirect
Via: 1.1 vegur
```

If you actually need a Node server instead of the built-in static server, switch over to [create-react-app with a Node server on Heroku](https://github.com/mars/heroku-cra-node).

**Comment by fbarbare** [comment]
Very good catch... I would never found that out 😂 
Works like a charm!
Thanks!
