### ISSUE TITLE
Browser cache & auto-versioning

### ISSUE THREAD

**Issue by asibilia** [mars/create-react-app-buildpack#40]
Mobile browsers are not loading the new `CSS` file when a new build is deployed. 

For example, all my app styles are compiled into `style/style.css` and after every successful deploy I need to tell my users to delete their browser cache so that the new styles will be loaded. 

Has anyone else seen this or know a workaround? Thanks!

**Comment by fbarbare** [comment]
If using create react app to generate your files and do your deployments, it hashes the generated files automatically, so you shouldn't have this problem. How are your deployments configured?

**Comment by asibilia** [comment]
@fbarbare Hmm, strange. Can you be a little more specific about my deployment configuration? I just have a `static.json` file that looks like this: 
```
{
  "root": "build/",
  "clean_urls": false,
  "routes": {
    "/**": "index.html"
  }
}
```
Is that what you're looking for?

Thanks!

**Comment by fbarbare** [comment]
@asibilia Do you have any link to your repo?
Do you have any procfile?
Could you give us your package.json file?

**Comment by asibilia** [comment]
@fbarbare 

* No procfile
* `package.json`:
```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "chai": "^3.5.0",
    "chai-jquery": "^2.0.0",
    "css-loader": "^0.26.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "jquery": "^2.2.1",
    "jsdom": "^8.1.0",
    "mocha": "^2.4.5",
    "node-sass": "^3.13.1",
    "npm-run-all": "^4.0.2",
    "react-scripts": "0.9.4",
    "sass-loader": "^4.0.2",
    "style-loader": "^0.13.1",
    "webpack": "^1.12.9",
    "webpack-dev-server": "^1.14.0"
  },
  "dependencies": {
    "axios": "^0.15.2",
    "babel-core": "^6.24.0",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.24.0",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-1": "^6.22.0",
    "css-loader": "^0.26.4",
    "file-loader": "^0.9.0",
    "firebase": "^3.7.4",
    "lodash": "^3.10.1",
    "moment": "^2.18.1",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "react-ga": "^2.1.2",
    "react-modal": "^1.7.3",
    "react-notification-system": "^0.2.13",
    "react-redux": "^4.0.0",
    "react-router": "^2.8.1",
    "react-sparklines": "^1.6.0",
    "redux": "^3.0.4",
    "redux-form": "^6.6.0",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.2.0",
    "shortid": "^2.2.8",
    "style-loader": "^0.13.2",
    "url-loader": "^0.5.8",
    "webpack-dev-server": "^1.16.3"
  },
  "scripts": {
    "build-css": "node-sass public/style/ -o public/style/",
    "watch-css": "npm run build-css && node-sass public/style/ -o public/style/ --watch --recursive",
    "start-js": "react-scripts start",
    "start": "npm-run-all -p watch-css start-js",
    "build": "npm run build-css && react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

**Comment by mars** [comment]
create-react-app does support [using a pre-processor like SASS](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc). I think the reason you're having caching issues is because your `node-sass` build is not within `src/` directory.

Follow those directions for [using a pre-processor](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc) in the main create-react-app docs, and if you continue to have problems, look into the [create-react-app issues](https://github.com/facebookincubator/create-react-app/issues?utf8=✓&q=is%3Aissue%20) for folks with similar problems or to file a new issue.

It's also possible to fix this by adding a cache-busting hash to the final `style.css` filename with a library like [Hashmark](https://github.com/keithamus/hashmark), but I would suggest utilizing the conventions provided by create-react-app instead of putting together your own CSS toolchain.

**Comment by fbarbare** [comment]
Your build process is not really straight forward.. You are adding the generated CSS to the public folder.
Create React App only copy/pastes the files in the public folder to the build one, without changing them apart from the index.html which gets processed.
To have the the hash included in your file automatically, you'll need to stop using SASS and import your CSS files directly from you JS files (The default example of CRA is a good example on how to do it.)

If however you still want to use SASS, you'll either have to add a random - or not - hash you css file when copying it, either eject and modify the webpack config for supporting SASS.

**Comment by asibilia** [comment]
Ah, awesome. Thanks guys, I appreciate all the help!
