### ISSUE TITLE
Serve 404 status code with react-router

### ISSUE THREAD

**Issue by pflenker** [mars/create-react-app-buildpack#43]
Hi,

I am using react-router for my routing, so far successfully. In my  routes, I was also able to define a fallback route for 404 pages, which also works perfectly.

However, it seems that we always return 200, even on those 404 routes, which is something I'd like to avoid for SEO reasons.

The only solution I found so far is explicitly defining the routes in the static.json instead of using `**/`, redirecting all of them to index.html - but that comes with the drawback of having the route definitions duplicated. Also, there is a high risk about forgetting amending the static.json when I introduce a new page, which would mean that a "valid" page that is normally rendered would return 404.

Any help would be appreciated.

Best regards,

Philipp

**Comment by mars** [comment]
Hello @pflenker,

Serving meaningful status codes on initial page load requires serve-side logic. This is a universal limitation of single-page apps (SPA), where the browser renders the JavaScript app. The browser will always get a `200` success response for any route served with the javascript app.

Your solution to encode some routing logic on the server in `static.json` sounds brittle, but it is the only way that **create-react-app-buildpack** can support sending such response code variations from the server.

The universal solution to this is server-side rendering: *run the routing code on the server*. SSR is not supported directly by **create-react-app** nor this buildpack.

I am a strong proponent of SSR. It's good for initial render performance, it's good for accessibility, & it's good for SEO. Because of the profusion of technology & techniques to accomplish this, it's challenging to put all the pieces together.

I highly recommend [Next.js on Heroku](https://github.com/mars/heroku-nextjs) to build React-based universal (server-rendered) web apps. Next does necessarily impose its own router & app architecture to accomplish its goals. Consider migrating your React components/pages to Next!

**Comment by pflenker** [comment]
Thank you for this thorough reply! I will check it out!
