### ISSUE TITLE
Running into a production but that I can't pin point 

### ISSUE THREAD

**Issue by firaskrichi** [mars/create-react-app-buildpack#47]
I am running into this error in Production. 

I don't have any errors locally, but as soon as I deploy to heroku there's an error and some pages are not accessible. 

I am trying to deploy to my dev. server on heroku to see the error message there, but it seems my env. is prod. even in my dev server with env. valiable ENV=DEVELOPMENT. 

Do you know how I can see what's causing the issue in my heroku dev. server? 

Thank you! 

reactProdInvariant.js:31 Uncaught (in promise) Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at n (reactProdInvariant.js:31)
    at o (instantiateReactComponent.js:74)
    at r (ReactChildReconciler.js:44)
    at a (traverseAllChildren.js:77)
    at a (traverseAllChildren.js:93)
    at o (traverseAllChildren.js:172)
    at Object.instantiateChildren (ReactChildReconciler.js:74)
    at h._reconcilerInstantiateChildren (ReactMultiChild.js:193)
    at h.mountChildren (ReactMultiChild.js:226)
    at h._createInitialChildren (ReactDOMComponent.js:697)
﻿

**Comment by mars** [comment]
This buildpack will always produce an optimized production build. This is by design.

If you need something more custom, then you can switch to [CRA with Node server](https://github.com/mars/heroku-cra-node) where you can setup the `heroku-postbuild` hook in `package.json` to build the bundle however you like.

**Comment by mars** [comment]
Sorry it's early & I misread the real problem here…

Did you follow that link to the description of the invariant violation? Seems like you have an ill-defined component somewhere.

You have an inconsistency in your local dev environment if it does not throw the error locally. Perhaps reset your npm modules locally `rm -rf node_modules/ && npm install`. Also try building the production bundle locally to reproduce the error `npm run build`.

**Comment by firaskrichi** [comment]
Nice thank you! Is there a way to push a dev. environment to heroku and see the error messages on the app-dev on heroku?

**Comment by mars** [comment]
This buildpack will always produce an optimized production build.

If you can't reproduce an error locally, then you have a disparity between local & deployment. The two things that could cause this are:

* **Different dependencies** are defined in `package.json` than what is actually installed in `node_models/`
   * Fix locally with: `rm -rf node_modules/ && npm install`
* **Uncommitted changes** exist in the local directory
   * Check locally: `git status` and then `git commit` any differences

**Comment by firaskrichi** [comment]
gotcha! Thanks @mars !
