### ISSUE TITLE
404 error with static.json but no 404 error when static.json is not included

### ISSUE THREAD

**Issue by msuzoagu** [mars/create-react-app-buildpack#49]
I am stumped by an error that occurred while I was attempting to deploy a react-js app, which was created with create-react-app, to heroku.

1). When I included a static.json file as per the instructions given [here](https://github.com/mars/create-react-app-buildpack#customization) for deploying a create-react-app to heroku, i got a 404 error. 

2). When static.json was not include, deployment goes well.

3). This is what the included static.json file looked like. 

{
 "root": "build/",
 "https_only": true,
 "headers": {
   "/**": {
     "Strict-Transport-Security": "max-age=7776000"
   }
 },
 "proxies": {
   "/api/": {
     "origin": "${API_URL}"
   }
 }
}

Thanks!

**Comment by mars** [comment]
Thanks for posting here @msuzoagu ,

Please confirm, the React app works locally with `npm start`?

What URL returns the 404 error?

What do the app's logs show? (`heroku logs`)

What does the build log show? (output from `git push heroku …`)

What does the `package.json` contain? (Especially in the  `scripts` and `homepage`  sections)

Does the repo contain a `Procfile`? If so what does it contain?

**Comment by bancura** [comment]
I am having the same issue as @msuzoagu, was this ever resolved?

My app was created using create-react-app and runs locally.  It also runs in heroku without the static buildpack and static.json file.  I was previously using CORS for my api calls but was hoping to use a proxy instead.

The issue appears to be a 403 error: "directory index of "./build/" is forbidden".  The file build/index.html exists but this almost looks as though nginx (if I am understanding this correctly) is looking for a directory.

Here is one config I have tried.  Also tried removing the proxies but same result.
```
{
  "root": "build/",
  "proxies": {
    "/api/": {
      "origin": "${REACT_APP_API_URL}"
    }
  }
}
```

Removing the 'root' results in a 404 which is also interesting because I think I read that this is the default.  I am not using react router but some of the posts I have read talk about, in case that comes in to play.

Thanks for the awesome create-react-app buildpack, was able to get things deployed very quickly!  I am pretty new to this so the help is appreciated!

**Comment by mars** [comment]
Hi @bancura, welcome!

It's pretty much impossible to help diagnose these kinds of errors without more technical details about your deployment. (This issue was originally closed because the poster never responded with diagnostic info.)

So, please answer the following questions. In your app's working directory, please reply with the full output from each of these commands:

```bash
ls -hal
```

```bash
ls -hal build/
```

```bash
git status
```

```bash
heroku buildpacks
```

```bash
cat package.json
```

```bash
# If this file exists in your project,
cat Procfile
```


Regarding:

> Removing the 'root' results in a 404 which is also interesting because I think I read that this is the default. I am not using react router but some of the posts I have read talk about, in case that comes in to play.

That `"root"` entry is in the default `static.json`, but when you add that file yourself, it replaces that default file. **`"root": "build/"` must be present for this buildpack to deploy a functional site.**

**Comment by bancura** [comment]
Thanks for the quick reply!  Here's the output for these commands.  Supporting this must be tricky so I understand if there's not enough to go on.

```
ls -hal
drwxr-xr-x   12 myuser  staff   408B Sep  3 10:16 .
drwxr-xr-x    9 myuser  staff   306B Jul  3 10:53 ..
drwxr-xr-x   15 myuser  staff   510B Sep  3 14:02 .git
-rw-r--r--    1 myuser  staff    53B Sep  2 16:01 .gitignore
-rw-r--r--    1 myuser  staff    79K Jul  3 10:53 README.md
drwxr-xr-x    6 myuser  staff   204B Sep  2 15:58 build
drwxr-xr-x  788 myuser  staff    26K Sep  2 15:48 node_modules
-rw-r--r--    1 myuser  staff   207K Aug 19 13:07 package-lock.json
-rw-r--r--    1 myuser  staff   680B Aug 19 13:07 package.json
drwxr-xr-x    4 myuser  staff   136B Jul  3 10:53 public
drwxr-xr-x   12 myuser  staff   408B Aug 19 13:07 src
-rw-r--r--    1 myuser  staff   102B Sep  3 10:25 static.json
```
```
ls -hal build/
drwxr-xr-x   6 myuser  staff   204B Sep  2 15:58 .
drwxr-xr-x  12 myuser  staff   408B Sep  3 10:16 ..
-rw-r--r--   1 myuser  staff   196B Sep  2 15:58 asset-manifest.json
-rw-r--r--   1 myuser  staff    24K Sep  2 15:58 favicon.ico
-rw-r--r--   1 myuser  staff   378B Sep  2 15:58 index.html
drwxr-xr-x   4 myuser  staff   136B Sep  2 15:58 static
```
In troubleshooting this I was pushing (many) changes to static.json directly to heroku master but not my private github repo so i'm a bit ahead until i clean up
```
git status
On branch master
Your branch is ahead of 'origin/master' by 11 commits.
  (use "git push" to publish your local commits)
nothing to commit, working tree clean
```
```
heroku buildpacks
=== pristine-cuyahoga-valley-44652 Buildpack URL
https://github.com/heroku/heroku-buildpack-static.git
```
```
cat package.json
{
  "name": "myapp",
  "version": "0.1.0",
  "private": true,
  "proxy": "http://localhost:3001",
  "dependencies": {
    "axios": "^0.16.1",
    "flexboxgrid": "^6.3.1",
    "material-ui": "^0.18.6",
    "moment": "^2.18.1",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-masonry-component": "^5.0.7",
    "react-redux": "^5.0.5",
    "react-tap-event-plugin": "^2.0.1",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "react-scripts": "0.9.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

I am not using a Procfile right now.

Thanks again for your time.

**Comment by mars** [comment]
> `https://github.com/heroku/heroku-buildpack-static.git`

There's the issue. The buildpack needs to be this one:

```bash
heroku buildpacks:set https://github.com/mars/create-react-app-buildpack.git
```

Then, deploy with the new buildpack:

```bash
git commit --allow-empty -m 'Switch to create-react-app-buildpack'
git push heroku master
```

**Comment by bancura** [comment]
Oh wow...I really made a mess...that did it!  I definitely changed this when reading about the static build pack.  I am new to Heroku and was treating the build packs as additive.

Thanks again for the help today!

**Comment by mars** [comment]
That's great to hear. 🍻

Note that you can [set multiple buildpacks on a Heroku app](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app), but in the case of this buildpack, it's already [made of multiple buildpacks](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#user-content-architecture-) including Node & static site.

**Comment by bancura** [comment]
Gotcha, thanks again.  

Cheers 🍻

**Comment by justinkchen** [comment]
So I posted in the create-react-app-buildpack about this, but I am getting the same behavior.  It works totally fine with `npm start` but returns 404 if I try to additively add `node/js` and `static` buildpacks....if i use the `create-react-app-buildpack` it works fine...but some of the node_module packages get served weird or minified weird and end up being buggy (only one I know of so far has been the BigNumber.js package).  What exactly does the `create-react-app-buildpack` do to the files that might be causing this?

**Comment by mars** [comment]
@justinkchen create-react-app-buildpack already includes the Node and Static buildpacks; checkout the [architecture](https://github.com/mars/create-react-app-buildpack#user-content-architecture-) for details. The main reason people have build problems is because they try to add or manipulate the buildpack composition without understanding these details.

create-react-app-buildpack basically deploys a static web server for the React app. If you need to run a Node server, switch to a pure Node approach: [heroku-cra-node](https://github.com/mars/heroku-cra-node).

**Comment by wiss123456789** [comment]
you should put the proxies like this :
{
"root": "build/",
"https_only": true,
"headers": {
"/**": {
"Strict-Transport-Security": "max-age=7776000"
}
},
"proxies": {
"/api/": {
"origin": "${API_URL}/api"
}
}
}
