### ISSUE TITLE
How to remove source maps?

### ISSUE THREAD

**Issue by lavrton** [mars/create-react-app-buildpack#59]
Are there any ways to disable/remove them?
It will be nice if I can just set `source_map_enabled: false` in static.json.

**Comment by mars** [comment]
What's your motivation to make this change? Curious if this is a build time issue, a bandwidth concern, or something else.

Your specific suggestion would not apply here, because `static.json` is config for the web server, not javascript/create-react-app concerns.

Found a [pertinent discussion](https://github.com/facebookincubator/create-react-app/issues/2005) about making such a customization through create-react-app.
As mentioned there, you may eject & modify webpack config to avoid generating source maps at all.

Otherwise, the inner & main buildpack could be forked and modified to delete that file after build. See [architecture](https://github.com/mars/create-react-app-buildpack#user-content-architecture-) for how these pieces fit together.

**Comment by lavrton** [comment]
@mars I just don't want to show full source code in production mode.

In other projects where I use `create-react-app` I manually remove `*.map` files as build step. This is suggested solution (https://github.com/facebookincubator/create-react-app/pull/2742#issuecomment-313658034).

I think `create-react-app-buildpack` can do this too. Just need to delete `*.map` files.

**Comment by mars** [comment]
That's not a convincing reason for why I should add such a feature. You're welcome to eject or fork the buildpack to do this.

**Comment by lavrton** [comment]
I just found that `create-react-app-buildpack`  use `npm run build`. So to remove sources maps I can simply update `build` script to:
```
"build": "react-scripts build && rm build/static/js/*.map",
```

**Comment by mars** [comment]
Thanks for following-up @lavrton. Glad to see the fix ended up being so simple.

**Comment by hugomosh** [comment]
Is there a way to just skip/avoid some files to the sourcemap?

**Comment by JonathanFu** [comment]
@hugomosh 
There is a simple one I found in other place.
We can now disable sourcemap with putting below setting in a `.env` file (at the root of the project):
`GENERATE_SOURCEMAP=false`

**Comment by serdarkaraca** [comment]
SET GENERATE_SOURCEMAP=false
npm run build
