### ISSUE TITLE
Heroku build fails, cannot resolve file or directory

### ISSUE THREAD

**Issue by khalibloo** [mars/create-react-app-buildpack#60]
It's my first attempt to use this buildpack, I'm likely doing something wrong. Building locally works fine, but building on Heroku (during deployment) fails with the error message 
`> react-scripts build
Creating an optimized production build...
Failed to compile.
Module not found: Error: Cannot resolve 'file' or 'directory' ./reducers in /tmp/build_7f9f3ebfb17d163d074f6ac7679c2d53/khalibloo-blah-8dde436/src`

I'm certain there are no uncommitted changes. I saw a similar issue on #17. Something to do with case sensitivity. Is it possible I didn't miss something after all?

**Comment by mars** [comment]
All I can guess based on the error is that the reference to `./reducers` directory is broken because either capitalization of the `import` statement doesn't match what's committed in git or is otherwise missing.

Without access to the code you're trying to deploy, it's very difficult to help further. Would you share a link to your source code repo? Feel free to collaborate only me @mars to help diagnose.

**Comment by khalibloo** [comment]
When I couldn't get it to work, I moved the project to a Django backend instead. I was on a tight schedule. The code isn't open source unfortunately. And I'm not allowed to share. However, it's really helpful to know for sure that the issue is in my code. Thanks a lot.

Just now, I tried the sample Todo app from react-redux. It worked smoothly without any issues when I deployed to Heroku with your buildpack.

I then stripped down the original project to its bare bones. It worked without any issues as well. I'll build on it from there. The project uses typescript, so maybe it was some stale compiled js file that was the source of the broken reference.

Thank you very much for your help.
