### ISSUE TITLE
Local committed changes not reflected in app after successful build

### ISSUE THREAD

**Issue by ryan0122** [mars/create-react-app-buildpack#66]
I was able to successfully install, run, and build the create react app.
I made some simple changes adding new modules and some navigation elements.
I'm able to push my changes to heroku and initiate a build. After the build successfully completes and I navigate to my app (https://mackweb-ui.herokuapp.com/) I do not see the new changes the I have made. 

Here is my build log:
`
-----> React.js (create-react-app) multi app detected
-----> Configure create-react-app build environment
       Using `NODE_ENV=development`
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-multi.git
=====> Detected Framework: Multipack
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
=====> Detected Framework: Node.js
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       NODE_VERBOSE=false
       NODE_ENV=development
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 6.x...
       Downloading and installing node 6.11.2...
       Using default npm version: 3.10.10
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)
-----> Building dependencies
       Installing node modules (package.json)
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
=====> Downloading Buildpack: https://github.com/mars/create-react-app-inner-buildpack.git
=====> Detected Framework: React.js (create-react-app)
       Using existing `static.json`
       Enabling runtime environment variables
> mackweb-ui@0.1.0 build /tmp/build_06148eb771d366033688df3c0092e4c0
> react-scripts build
Creating an optimized production build...
Compiled successfully.
File sizes after gzip:
  84.36 KB  build/static/js/main.fc0dfb75.js
  288 B     build/static/css/main.cacbacc7.css
The project was built assuming it is hosted at  https://mackweb-ui.herokuapp.com.
You can control this with the homepage field in your package.json.
The build folder is ready to be deployed.
You may serve it with a static server:
  npm install -g serve
  serve -s build
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-static.git
=====> Detected Framework: Static HTML
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
-----> Installed directory to /app/bin
Using release configuration from last framework (Static HTML).
-----> Discovering process types
       Procfile declares types     -> (none)
       Default types for buildpack -> web
-----> Compressing...
       Done: 39.2M
-----> Launching...
       Released v10
       https://mackweb-ui.herokuapp.com/ deployed to Heroku
`

Another interested observation is that my app doesn't even load in firefox.....

https://mackweb-ui.herokuapp.com/

**Comment by mars** [comment]
I just performed a fresh install of create-react-app and deployed a new app using the [Quick Start instructions](https://github.com/mars/create-react-app-buildpack#user-content-quick-start). Then, I visited the app in two browsers, Safari & Firefox. Finally, I made a small change to `App.js`, redeployed, and that change appears when I refresh the site.

So, because this buildpack + the default create-react-app code does not exhibit the issue, there must be something going on in your specific app to make this happen.

Based on your description, perhaps you forgot to commit the changes you made? Check with:

```bash
git status
```

A few notes about how caching works with create-react-app:

* Everytime the app is rebuilt by `npm run build`, such as when deploying to Heroku, the cache-busting hash changes for the CSS & JS bundles, e.g. `/static/js/main.f0144275.js` is updated to `/static/js/main.67e36665.js`. The references in `index.html` are automatically updated to use these new assets. As a result, caching is enabled by default. Disabling it with no-cache headers will make performance suffer.
* Recent versions of create-react-app began including a Service Worker to improve low-connectivity & offline performance. This might be causing issues or at least confusing the debugging process. See the docs for [Making a Progressive Web App](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#user-content-making-a-progressive-web-app)

**Comment by ryan0122** [comment]
Thank you for your reply. I tried creating a new app with the build pack and it works as expected.

**Comment by d4rky-pl** [comment]
@ryan0122 this might've been a problem with service workers. 

See https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app if you have no idea what service workers are and just want to disable them and avoid this issue.
