### ISSUE TITLE
npm ERR! missing script: build (ejected)

### ISSUE THREAD

**Issue by tonymckendry** [mars/create-react-app-buildpack#80]
I'm attempting to do my first deploy and continue to get the above error during the push process to the Heroku:master branch - I have verified that my package.json contains a build script, which references a file in the scripts folder in the root of the project (this is all just the standard stuff that comes with create-react-app, I haven't touched it) - any suggestions?

**Comment by mars** [comment]
Hi @tonymckendry,

Apps generated by create-react-app will deploy as-is without errors. No further config needed, so something has been misconfigured in this case. You say you didn't touch **package.json**, but I don't know of another way such an error would occur. Did you use some other tool that would change the package?

Try generating a new app with `create-react-app this-is-a-test` and compare its **package.json** to yours. What is different in the `scripts` section?

If you've already reached the last step of [troubleshooting](https://github.com/mars/create-react-app-buildpack#user-content-troubleshooting), then please go ahead an post a link to you GitHub repo or at least you **package.json** file contents, so that I can try to help further.

**Comment by tonymckendry** [comment]
Mars,
I'm realizing that I did at one point "eject" the create-react-app stuff so that I could add babel+config in - guessing that is probably what is causing my issue. Hopefully all hope is not lost!

Here is my package.json

```
{
  "name": "mercantyle_landing_page",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "autoprefixer": "7.1.6",
    "babel-core": "6.26.0",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-loader": "7.1.2",
    "babel-preset-react-app": "^3.1.0",
    "babel-runtime": "6.26.0",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "create-react-class": "^15.6.2",
    "css-loader": "0.28.7",
    "dotenv": "4.0.0",
    "eslint": "4.10.0",
    "eslint-config-react-app": "^2.0.1",
    "eslint-loader": "1.9.0",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "7.4.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "fs-extra": "3.0.1",
    "html-webpack-plugin": "2.29.0",
    "jest": "20.0.4",
    "material-ui": "^0.19.4",
    "mobx": "^3.3.1",
    "mobx-react": "^4.3.4",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.8",
    "promise": "8.0.1",
    "raf": "3.4.0",
    "react": "^16.0.0",
    "react-dev-utils": "^4.2.1",
    "react-dom": "^16.0.0",
    "react-layout-components": "^3.0.6",
    "react-slick": "^0.16.0",
    "react-window-mixins": "0.0.7",
    "slick-carousel": "^1.8.1",
    "sparkpost": "^2.1.2",
    "style-loader": "0.19.0",
    "sw-precache-webpack-plugin": "0.11.4",
    "url-loader": "0.6.2",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.3",
    "webpack-manifest-plugin": "1.3.2",
    "whatwg-fetch": "2.0.3"
  },
  "scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "test": "node scripts/test.js --env=jsdom"
  },
  "proxy": "http://localhost:3001",
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,mjs}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.{js,jsx,mjs}",
      "<rootDir>/src/**/?(*.)(spec|test).{js,jsx,mjs}"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx|mjs)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|mjs|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    },
    "moduleFileExtensions": [
      "web.js",
      "mjs",
      "js",
      "json",
      "web.jsx",
      "jsx",
      "node"
    ]
  },
  "babel": {
    "plugins": [
      "transform-decorators-legacy"
    ],
    "presets": [
      "react-app"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  }
}

```

**Comment by mars** [comment]
Since the app has been ejected, pretty much anything can go wrong 🙃 My focus with this buildpack is to help folks deploy the zero-configuration way. When you choose to eject, my ability to help plummets 📉

Clearly the build script entry is there: `"build": "node scripts/build.js"`. Is that `scripts/` directory committed to git so that it's available when pushed to Heroku? For that matter, are all your changes committed to git?

Does the build work locally with `npm run build`? If it does work locally, then there must be an inconsistency with what is in the git repo. If it does not work locally, then the build issues have nothing to do with deployment; debug locally to get it working.

Last resort: try resetting your working directory to the un-ejected state using the **package.json** from a clean create-react-app. Then, eject and gradually add your changes, testing with `npm run build` along the way to ensure each change you make results in a working app.

**Comment by tonymckendry** [comment]
Thank you so much for getting back to me so promptly, I will give these steps a shot at my next opportunity and report back.

**Comment by mars** [comment]
Closing this because it’s not an issue with this buildpack.

Wishing you luck @tonymckendry to figure out the ejected config problem 🍀
